// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFzzPdcx-6RPlDQJ0oyAIKpZgJnnxD-8U',
    appId: '1:765303115201:web:a5a78b0f6b79818c77f340',
    messagingSenderId: '765303115201',
    projectId: 'wakala-45dad',
    authDomain: 'wakala-45dad.firebaseapp.com',
    storageBucket: 'wakala-45dad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpobRt7r8GcbsKjmeInM-PvcNHBaG4iBQ',
    appId: '1:765303115201:android:0118c20ddae9672377f340',
    messagingSenderId: '765303115201',
    projectId: 'wakala-45dad',
    storageBucket: 'wakala-45dad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2CvNVP13UXPyPxqLdQZmzpUQQMdTKuEQ',
    appId: '1:765303115201:ios:6bfe0b8e0e059ac977f340',
    messagingSenderId: '765303115201',
    projectId: 'wakala-45dad',
    storageBucket: 'wakala-45dad.appspot.com',
    iosBundleId: 'com.example.wakalaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2CvNVP13UXPyPxqLdQZmzpUQQMdTKuEQ',
    appId: '1:765303115201:ios:c4ece8596cb0515477f340',
    messagingSenderId: '765303115201',
    projectId: 'wakala-45dad',
    storageBucket: 'wakala-45dad.appspot.com',
    iosBundleId: 'com.example.wakalaApp.RunnerTests',
  );
}
